# Generated by Django 5.1.6 on 2025-03-01 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Наименование')),
                ('tank', models.IntegerField(verbose_name='Ёмкость топливного бака')),
                ('consumption_winter', models.FloatField(verbose_name='Расход топлива по зиме')),
                ('consumption_summer', models.FloatField(verbose_name='Расход топлива по лету')),
            ],
        ),
    ]
