# Generated by Django 5.1.6 on 2025-03-01 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='driver_license_category',
            field=models.IntegerField(choices=[(0, 'B'), (1, 'C')], default=0),
        ),
    ]
