# Generated by Django 5.1.6 on 2025-03-01 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0002_car_driver_license_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['name'], 'verbose_name': ('Автомобиль',), 'verbose_name_plural': ('Автомобили',)},
        ),
    ]
