volumes:
  dlwork_pgdata:
  dlwork_redisdata:

services:
  dlwork_database:
    image: postgres:latest
    ports:
      - "${DB_PORT_FORWARD}:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DB}
      POSTGRES_HOST: localhost
    volumes:
      - dlwork_pgdata:/var/lib/postgresql/data
    restart: always

  dlwork_django:
    build: .
    ports:
      - "${GUNICORN_PORT}:5000"
    environment:
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DJANGO_DEBUG: ${DJANGO_DEBUG}
      DJANGO_ALLOWED_HOST: ${DJANGO_ALLOWED_HOST}
      DB_DB: ${DB_DB}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      REDIS_HOST: ${REDIS_HOST}
      PYTHONUNBUFFERED: 1
    entrypoint: bash -c  "python manage.py collectstatic --noinput && python manage.py migrate && gunicorn --bind 0.0.0.0:5000 dellin_work.wsgi:application";
    volumes:
      - /home/dellinwt/static:/src/static
    depends_on:
      - dlwork_database
    restart: always

  dlwork_redis:
    image: redis:latest
    restart: always
    volumes:
      - dlwork_redisdata:/data

  dlwork_celery:
    build: .
    depends_on:
      - dlwork_redis
      - dlwork_django
    environment:
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DJANGO_DEBUG: ${DJANGO_DEBUG}
      DJANGO_ALLOWED_HOST: ${DJANGO_ALLOWED_HOST}
      DB_DB: ${DB_DB}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      REDIS_HOST: ${REDIS_HOST}
      PYTHONUNBUFFERED: 1
    command: celery -A dls worker -l info

  dlwork_celerybeat:
    build: .
    depends_on:
      - dlwork_redis
      - dlwork_django
    environment:
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DJANGO_DEBUG: ${DJANGO_DEBUG}
      DJANGO_ALLOWED_HOST: ${DJANGO_ALLOWED_HOST}
      DB_DB: ${DB_DB}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      REDIS_HOST: ${REDIS_HOST}
      PYTHONUNBUFFERED: 1
    command: celery -A dls beat -l info

  dlwork_bot:
    build: .
    environment:
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DJANGO_DEBUG: ${DJANGO_DEBUG}
      DJANGO_ALLOWED_HOST: ${DJANGO_ALLOWED_HOST}
      DB_DB: ${DB_DB}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      REDIS_HOST: ${REDIS_HOST}
      PYTHONUNBUFFERED: 1
    entrypoint: bash -c  "python manage.py runbot";
    depends_on:
      - dlwork_celery
      - dlwork_redis
    restart: always