volumes:
  dlwork_pgdata:
  dlwork_redisdata:

services:
  dlwork_database:
    image: postgres:latest
    ports:
      - "${DB_PORT_FORWARD}:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DB}
      POSTGRES_HOST: localhost
    volumes:
      - dlwork_pgdata:/var/lib/postgresql/data
    restart: always

  dlwork_redis:
    image: redis:latest
    restart: always
    volumes:
      - dlwork_redisdata:/data