# Generated by Django 5.1.6 on 2025-03-01 19:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('autos', '0003_alter_car_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время записи')),
                ('consumption', models.FloatField(verbose_name='Расход топлива')),
                ('odo', models.IntegerField(verbose_name='Пробег за рейс')),
                ('econ', models.FloatField(verbose_name='Экономия топлива')),
                ('burnout', models.IntegerField(verbose_name='Пережог топлива')),
                ('car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='autos.car', verbose_name='Транспортное средство')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Водитель')),
            ],
        ),
    ]
