# Generated by Django 5.1.6 on 2025-03-01 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='telegram_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='ID Telegram'),
        ),
    ]
