# Generated by Django 5.1.6 on 2025-03-01 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0001_initial'),
        ('profile_management', '0002_newuser_telegram_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='setting_last_auto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='autos.car', verbose_name='Последний автомобиль'),
        ),
        migrations.AddField(
            model_name='newuser',
            name='settings_last_fuel',
            field=models.IntegerField(blank=True, null=True, verbose_name='Последний остаток топлива'),
        ),
        migrations.AddField(
            model_name='newuser',
            name='settings_last_odo',
            field=models.IntegerField(blank=True, null=True, verbose_name='Последний пробег'),
        ),
    ]
