# Generated by Django 5.1.6 on 2025-03-01 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Наименование')),
            ],
            options={
                'verbose_name': ('Город',),
                'verbose_name_plural': ('Города',),
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Bases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Наименование')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bases.city')),
            ],
            options={
                'verbose_name': ('ОСП',),
                'verbose_name_plural': ('ОСП',),
                'ordering': ['name'],
            },
        ),
    ]
