# Generated by Django 5.1.6 on 2025-03-01 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bases', '0001_initial'),
        ('profile_management', '0002_newuser_telegram_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bases',
            new_name='Base',
        ),
    ]
