# Generated by Django 5.1.6 on 2025-03-01 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0001_initial'),
        ('bases', '0002_rename_bases_base'),
    ]

    operations = [
        migrations.AddField(
            model_name='base',
            name='autos',
            field=models.ManyToManyField(to='autos.car', verbose_name='Автомобили'),
        ),
    ]
