# Generated by Django 5.1.6 on 2025-03-01 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bases', '0003_base_autos'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='consumption_time',
            field=models.IntegerField(choices=[(0, 'Летний'), (1, 'Зимний')], default=1, verbose_name='Тип расхода топлива'),
        ),
    ]
